---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    provider: fabric8
    project: thursday-offer
    version: 1.0-SNAPSHOT
    group: flipkart2
  name: thursday-offer
data:
  application.properties: |
    # spring application properties file
    welcome = Hello from Kubernetes ConfigMap!!!
    dummy = some value
