---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: a8c5f80d33ddcf36cb9dbfcd9f63db922db902c1
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: menfashion
      version: 1.0-SNAPSHOT
      group: flipkart2
    name: menfashion
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: menfashion
      provider: fabric8
      group: flipkart2
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: a8c5f80d33ddcf36cb9dbfcd9f63db922db902c1
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=menfashion&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: menfashion
      version: 1.0-SNAPSHOT
      group: flipkart2
    name: menfashion
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: menfashion
        provider: fabric8
        group: flipkart2
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: a8c5f80d33ddcf36cb9dbfcd9f63db922db902c1
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=menfashion&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: menfashion
          version: 1.0-SNAPSHOT
          group: flipkart2
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: flipkart2/menfashion-funktor:snapshot-201026-124633-0560
          imagePullPolicy: IfNotPresent
          name: funktor
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: flipkart2/menfashion-trigger:snapshot-201026-124633-0560
          imagePullPolicy: IfNotPresent
          name: trigger
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
